version: '3.8'

volumes:
  nginx-website-file:
    name: nginx-website-file
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker_file/container/nginx_website/website_file
  nginx-website-config:
    name: nginx-website-config
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker_file/container/nginx_website/config
  mariadb-website-config:
    name: mariadb-website-config
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker_file/container/mariadb_website/config
  php-website-config:
    name: php-website-config
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker_file/container/php_website/config

services:
  nginx-website:
    container_name: nginx-website
    image: nginx:latest
    restart: always
    ports:
      - 8080:8080
      - 443:443
      - 80:80
    networks:
      - server_for_public
    environment:
      NGINX_HOST: "domain_name"
    volumes:
      - nginx-website-file:/usr/share/nginx/html
      - nginx-website-config:/etc/nginx/conf.d
      - /var/docker_file/logs/nginx_website/:/var/log/nginx

  mariadb-website:
    container_name: mariadb-website
    image: mariadb:latest
    restart: always
    networks:
      - server_for_public
    environment:
      MARIADB_ROOT_PASSWORD: "ROOT_PASSWD"
    expose:
      - "3306"
    volumes:
      - mariadb-website-config:/etc/mysql
      - /var/docker_file/logs/mariadb_website/:/var/log/mysql
      - /var/docker_file/container/mariadb_website/init.d/wordpress/:/docker-entrypoint-initdb.d

  php-8.1.18-fpm-website:
    container_name: php-8.1.18-fpm-website
    image: php:8.1.18-fpm
    restart: always
    networks:
      - server_for_public
    expose:
      - "9000"
    volumes:
      - nginx-website-file:/usr/share/nginx/html
      - php-website-config:/usr/local/etc/php
      - /var/docker_file/logs/php_website/:/var/log

networks:
  server_for_public:
    driver: bridge

